kind: pipeline
type: kubernetes
name: build-images

trigger:
  event:
    - push

image_pull_secrets:
  - DOCKER_CONFIG_JSON

steps:
  - name: build-api
    image: harbor.devops.indico.io/indico/drone-builder
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      registry: harbor.devops.indico.io
      repo: harbor.devops.indico.io/indico/project_fruitfly_finetune
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}.${DRONE_COMMIT_SHA}
      squash: true
      experimental: true
      context: .
      dockerfile: finetune/Dockerfile
    environment:
      DOCKER_BUILDKIT: 1
      POETRY_INSTALL_ARGS: ""
---
kind: pipeline
type: kubernetes
name: build-charts

depends-on:
  - build-images

concurrency:
  limit: 1 # allow 1 at most (dont over load chartmuseum)

trigger:
  event:
    - push

steps:
  - name: push helm charts
    image: alpine/helm:3.10.2
    commands:
      - echo https://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
      - apk update
      - apk add yq jq bash curl wget
      - wget -c https://github.com/shteou/helm-dependency-fetch/releases/download/v1.1.3/helm-dependency-fetch_1.1.3_Linux_x86_64.tar.gz -O - | tar -xz
      - export PATH=$${CWD}:$${PATH}
      - helm version
      - helm plugin install https://github.com/chartmuseum/helm-push --version 0
      - helm repo add --username $USERNAME --password $PASSWORD harborprod https://harbor.devops.indico.io/chartrepo/indico-charts
      - helm_scripts/update_image_tags.sh
      - helm_scripts/upload_helm_charts.sh "$DRONE_BRANCH-${DRONE_COMMIT_SHA:0:8}"

    environment:
      PYTHONUNBUFFERED: '1'
      IMAGE_TAG: ${DRONE_SOURCE_BRANCH/\//-}.${DRONE_COMMIT_SHA}
      HARBOR_API_TOKEN:
        from_secret: harbor_api_token
      HELM_EXPERIMENTAL_OCI: 1
      PASSWORD:
        from_secret: harbor_password
      USERNAME:
        from_secret: harbor_username

image_pull_secrets:
  - harbor_pull_secret
---
kind: secret
name: DOCKER_CONFIG_JSON
get:
  path: tools/drone/devops_harbor_pull_secret
  name: DOCKER_CONFIG_JSON
---
kind: secret
name: harbor_pull_secret
get:
  path: tools/drone/devops_harbor_pull_secret
  name: DOCKER_CONFIG_JSON 

---
kind: secret
name: harbor_username
get:
  path: tools/drone/harbor-push-token
  name: username

---
kind: secret
name: harbor_password
get:
  path: tools/drone/harbor-push-token
  name: password

---
kind: secret
name: harbor_api_token
get:
  path: tools/drone/harbor-api
  name: bearer_token