apiVersion: v2
name: project-fruitfly
description: A standalone Helm chart for project-fruitfly
appVersion: 0.1.0
version: 0.1.0
type: application
dependencies:
  - name: nvidia-device-plugin
    repository: https://nvidia.github.io/k8s-device-plugin
    version: 0.10.0