appName: project-fruitfly
defaultNamespace: "default"

imagePullSecret: harbor-pull-secret

storage:
  pvcName: read-write

sweepSetup:
  wandbApiKey: ""
  wandbProject: dataset-paper-sweeps-k8s-test
  wandbEntity: indico


sweeps:
  finetune:
    replicas: 1
    command: '["bash", "run_sweeps.sh"]'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 2Gi
        nvidia.com/gpu: 1
    env: {}
    priorityClassName: indico-gpu-critical
    image:
      repository: harbor.devops.indico.io/indico
      name: project_fruitfly_finetune
      # -- Filled in by the update_image_tags.sh script
      tag: <placeholder>
  layoutlm:
    replicas: 1
    command: '["bash", "run_sweeps.sh"]'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 2Gi
        nvidia.com/gpu: 1
    env: {}
    priorityClassName: indico-gpu-critical
    image:
      repository: harbor.devops.indico.io/indico
      name: project_fruitfly_layoutlm
      # -- Filled in by the update_image_tags.sh script
      tag: <placeholder>
  huggingface:
    replicas: 1
    command: '["bash", "run_sweeps.sh"]'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 2Gi
        nvidia.com/gpu: 1
    env: {}
    priorityClassName: indico-gpu-critical
    image:
      repository: harbor.devops.indico.io/indico
      name: project_fruitfly_huggingface
      # -- Filled in by the update_image_tags.sh script
      tag: <placeholder>
  

nvidia-device-plugin:
  image:
    repository: harbor.devops.indico.io/public-nvcr-proxy/nvidia/k8s-device-plugin
  imagePullSecrets:
    - name: "harbor-pull-secret"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: k8s.amazonaws.com/accelerator
            operator: Exists